# Site settings
title: JDE
subtitle: a digital portfolio
email: jaythan@jointley.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "https://github.com/jaythanelam/portfolio" # the subpath of your site, e.g. /blog
url: "https://github.com/jaythanelam" # the base hostname & protocol for your site
author:
street_address: 7712 Royal Harbour Circle
city: Oolteway
state: TN
zip_code: 37363
country: United States of America
phone: (571) 428-7176

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/jaythanelam
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/jaythan
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jaythan

# Build settings
markdown: kramdown
